### ISSUE TITLE
參考網站

### ISSUE THREAD

**Issue by RexYuan** [communityNTNU/communityntnu.github.io#1]
一些覺得視覺上很讚且認為適合一頁式宣傳的網站，歡迎增加擴建這個列表
- [Johns Hopkins University](https://www.jhu.edu/)

**Comment by wildskyf** [comment]
我喜歡這個概念！
![2016-01-24 22-06-20](https://cloud.githubusercontent.com/assets/6042803/12536665/b6b8ab86-c2e6-11e5-8058-d458cbe6c10d.png)
