### ISSUE TITLE
關於

### ISSUE THREAD

**Issue by RexYuan** [communityNTNU/communityntnu.github.io#2]
[我剛剛又在看了一下 我覺得已經沒什麼好改的了 覺得呢？](https://github.com/communityNTNU/communityntnu.github.io/wiki)

**Comment by wildskyf** [comment]
沒問題，除了專案那邊不用空格XD

**Comment by RexYuan** [comment]
直接改吧！

Wildsky Fann notifications@github.com 於 2016年1月24日 週日 下午9:47寫道：

**Comment by wildskyf** [comment]
放上去了(時隔一年XD
